### ISSUE TITLE
Font color is not applied in Options, Event, and Method names

### ISSUE THREAD

**Issue by yoshimis** [IgniteUI/help-topics#102]
The following Options, Event, and Method name's font color is not the same as older version. Older version used orange font color.

e.g.
http://www.igniteui.com/help/api/2016.2/ui.iggrid#options
http://www.igniteui.com/help/api/2016.2/ui.iggrid#events
http://www.igniteui.com/help/api/2016.2/ui.iggrid#methods

**Comment by ig-ealbert** [comment]
@yoshimis This seems to be a styling change in Tripwire.  It has nothing to do with the help-topics, which contain the content for the developer's guide help.  You could log a bug in TFS to Craig or Damyan, although this may be intentional.

**Comment by yoshimis** [comment]
Filed TFS bug 227992 and assigned to Craig.
