### ISSUE TITLE
Broken images in Grid topics

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#250]
Go here
http://staging.igniteui.local/help/iggrid-virtualization-overview?v=16.2
 
And here
http://staging.igniteui.local/help/iggrid-binding-to-webapi?v=16.2
(this one has two broken images)
 
http://staging.igniteui.local/help/iggrid-virtualization-overview?v=16.2

![image](https://cloud.githubusercontent.com/assets/9548226/24031175/c2e726b6-0ae9-11e7-8bff-039f507baea1.png)

![image](https://cloud.githubusercontent.com/assets/9548226/24031180/c7cfd010-0ae9-11e7-90f0-565e8637b6fa.png)

![image](https://cloud.githubusercontent.com/assets/9548226/24031186/cd944594-0ae9-11e7-9dd1-83bfca5198c7.png)

**Comment by MayaKirova** [comment]
Both seem fine locally and on dev. This will probably be fixed with one of the next builds on staging.

**Comment by ig-ealbert** [comment]
If it's working on dev and not staging, that means it was a bug with Tripwire, as Craig and Damyan just made some updates to it.  So in the meantime, @EmilTanev could you please test on dev?

**Comment by EmilTanev** [comment]
Verified the links above on dev 16.2
