### ISSUE TITLE
Grid - Link to topic displays "html"

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#251]
Go here
 
http://staging.igniteui.local/help/iggrid-virtualization-overview?v=16.2

Look for 
Feature Compatibility Matrix (igGrid).html

![image](https://cloud.githubusercontent.com/assets/9548226/24031315/90f62aca-0aea-11e7-8633-129b0e59735c.png)

**Comment by ig-ealbert** [comment]
Fixed in Japanese.
