### ISSUE TITLE
Broken images in igTreeGrid overview

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#258]
http://staging.igniteui.local/help/igtreegrid-overview?v=16.2#mvc-treegrid

![image](https://cloud.githubusercontent.com/assets/9548226/24041878/12178996-0b18-11e7-8369-accaa7fd4e42.png)

**Comment by EmilTanev** [comment]
Second one here

![image](https://cloud.githubusercontent.com/assets/9548226/24041946/68a60288-0b18-11e7-86e0-c4bd9aed3924.png)

**Comment by ig-ealbert** [comment]
This also seems to be fixed on dev (per Tripwire updates).
