### ISSUE TITLE
Topics tree flickers while scrolling the page on Edge

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/help-topics#263]
Open a help topic such as http://dev.igniteui.local/help/iggrid-overview on Edge

Start scrolling down and observe the topics tree to the left.

The whole content and its scrollbar constantly shuffles top and down a few pixels creating a flickering effect.

**Comment by damyanpetev** [comment]
Fixed. Weird z-index bug with fixed content. ref: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5752059/
