### ISSUE TITLE
igGrid/igDataSource Architecture Overview topic contains a badly formatted code snippet

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/help-topics#266]
Open http://dev.igniteui.local/help/iggrid-igdatasource-architecture-overview#related-content

Scroll down to Features -> Listing 3

The following code snippet has two minor issues - the identation and formatting can be better (no space after { and before } in the column settings, one tab missing for most lines)

The text <column definitions> is weirdly colorized

**Comment by rkaraivanov** [comment]
closed via #283
