### ISSUE TITLE
igGrid/igDataSource Architecture Overview topic contains obsolete and incorrect information

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/help-topics#267]
Open http://dev.igniteui.local/help/iggrid-igdatasource-architecture-overview#related-content

Scroll all the way down - the topic lists that the Grid/DataSource depend on jQuery 1.4.4 and jQuery UI 1.8.*  while Ignite UI  now depends on much higher versions of the two libraries.

The Note: below is also obsolete as we don't support jQuery templating anymore.

**Comment by rkaraivanov** [comment]
closed via #283
