### ISSUE TITLE
Sample links that should be removed or modified

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/help-topics#270]
- [x]  In the topic: http://dev.igniteui.local/help/iggrid-binding-to-webapi the sample that was available  here http://www.igniteui.com/grid/rest-editing (Samples section) is no longer available.

- [x] In the topic http://dev.igniteui.local/help/iggrid-column-hiding-enabling-column-hiding#samples the two sample links are both broken - there are no longer such sample.

- [x] In the topic http://dev.igniteui.local/help/iggrid-column-hiding-grid-events#samples the sample link should be removed as the sample is no longer available.

- [x] In the topic: http://dev.igniteui.local/help/iggrid-groupby-overview#related-content the sample link in the end should be _renamed_ to GroupBy as it is called in the samples browser.
- [x] In the topic http://dev.igniteui.local/help/iggrid-hiding-column-chooser#samples . The sample link is for a sample that's no longer available.

- [x] In the topic http://dev.igniteui.local/help/iggrid-columnmoving-overview#samples . The sample link is for a sample that's no longer available.

- [x] In the topic http://dev.igniteui.local/help/iggrid-columnmoving-enabling#samples . The sample link is for a sample that's no longer available.

- [x] In the topic http://dev.igniteui.local/help/iggrid-columnmoving-configuring#samples . The sample link is for a sample that's no longer available.

- [x] In the topic http://dev.igniteui.local/help/iggrid-columnmoving-movingcolumnsprogrammatically#samples . The sample link is for a sample that's no longer available.

- [x] In the topic http://dev.igniteui.local/help/iggrid-column-summaries-events#samples . The sample link is for a sample that's no longer available.

- [x] In the topic http://dev.igniteui.local/help/iggrid-filtering there are three sample links and at least two of the samples are no longer available. There should be only 1 link to the remaining Filtering sample in the sample's browser.

- [x] In the topic http://dev.igniteui.local/help/iggrid-multicolumnheaders-configuring#samples . Multi-Column Headers sample link should be removed. The other one exists and should remain as the only sample link for this topic.

- [x] In the topic http://dev.igniteui.local/help/igupload-using-client-side-events. The sample in the "Related links" area should be removed.

- [x] In the topic http://dev.igniteui.local/help/igupload-using-server-side-events. The sample link for the "igUpload API and Events Sample" should be removed.
The "AddStartingUploadEventHandler", "AddStartingUploadEventHandler", "ServerMessage" links should lead to the MVC API. Example for "AddStartingUploadEventHandler": http://dev.igniteui.local/help/infragistics.web.mvc~infragistics.web.mvc.uploadprogressmanager~addstartinguploadeventhandler

- [x] in the topic: http://dev.igniteui.local/help/conditional-and-advanced-templating-with-angularjs. The "JsRender Integration" sample link should be replaced with topic link http://dev.igniteui.local/help/iggrid-jsrender-integration

- [x] In the topic: http://dev.igniteui.local/help/using-ignite-ui-with-typescript. Grid, Editors and DataChart Typescript sample links should be removed

- [x] In the topic: http://dev.igniteui.local/help/ighierarchicalgrid-binding-to-dataset. "DataSet binding" sample link should be removed

 - [x] In the topic: http://dev.igniteui.local/help/ighierarchicalgrid-binding-to-local-data. "columnLayouts.key" link is broken and should lead to the API. Link for "fields.xpath" should be added.

 - [x] In the topic: http://dev.igniteui.local/help/ighierarchicalgrid-binding-to-rest-services. "igGrid REST Editing" sample link should be removed. 

 - [x] In the topic: http://dev.igniteui.local/help/ighierarchicalgrid-binding-to-webapi. "igGrid REST Editing" sample link should be removed. 

 - [x] In the topic: http://dev.igniteui.local/help/iggrid-unboundcolumns-setting-column-as-unbound the sample link should be removed.

- [x] In the topic http://dev.igniteui.local/help/iggrid-unboundcolumns-populating-with-data-overview the sample link should be removed.

- [x] In the topic http://dev.igniteui.local/help/iggrid-unboundcolumns-populating-with-data-locally#overview the sample link should be removed.

- [x] In the topic http://dev.igniteui.local/help/iggrid-unboundcolumns-populating-with-data-remotely#samples the sample link should be removed.

- [x] In the topic http://dev.igniteui.local/help/iggrid-unboundcolumns-rendering-calculated-values#samples the sample link should be removed.

- [x] In the topic http://dev.igniteui.local/help/iggrid-unboundcolumns-optimize-performance the sample link should be removed.

- [x] In the topic http://dev.igniteui.local/help/iggrid-unboundcolumns-known-issues#chaining-remote-url the sample link should be removed.

- [x] In the topic http://dev.igniteui.local/help/iggrid-enabling-row-selectors#samples the sample link should be _changed_ to link to http://dev.igniteui.local/16-2/grid/selection .
- [x] In the topic  http://dev.igniteui.local/help/igpopover-overview#samples the Basic Usage sample link should be changed to http://staging.igniteui.local/16-2/popover/overview
- [x] In the topic http://dev.igniteui.local/help/configuring-igpopover#samples sample link for Basic Usage should be changed to http://staging.igniteui.local/16-2/popover/overview
- [x] In the topic: http://dev.igniteui.local/help/extending-iggrid-modal-dialog#samples the sample should be modified
- [x] In the topic http://dev.igniteui.local/help/styling-igpopover  the Basic Usage sample link should be changed to http://staging.igniteui.local/16-2/popover/overview
- [x] In the topic: https://dev.igniteui.local/help/iggrid-virtualization-overview the samples should be removed

 - [x] In the topic: https://dev.igniteui.local/help/ighierarchicalgrid-grouping-overview. "Grouping Customization" sample link should be removed

 - [x] In the topic: https://dev.igniteui.local/help/ighierarchicalgrid-grouping-custom. "Grouping Customization" sample link should be removed

 - [x] In the topic: https://dev.igniteui.local/help/ighierarchicalgrid-multicolumnheaders-configuring. "Multi-Column Headers" sample link should be removed

- [x] In the topic: http://dev.igniteui.local/help/iggrid-updating the first sample should be renamed to *Editing* and the second to *Live Updates* ,

 - [x] In the topic: http://www.igniteui.com/hierarchical-grid/selection-rowselectors. The "Row Selectors" sample link should point to http://www.igniteui.com/hierarchical-grid/selection-rowselectors

 - [x] In the topic: http://dev.igniteui.local/help/ighierarchicalgrid-configuring-rowselectors. The "Row Selectors" sample link should point to http://www.igniteui.com/hierarchical-grid/selection-rowselectors

 - [x] In the topic: http://dev.igniteui.local/help/ighierarchicalgrid-rowselectors-events. The "Row Selectors" sample link should point to http://www.igniteui.com/hierarchical-grid/selection-rowselectors

- [x] In the topic: http://dev.igniteui.local/help/igtreegrid-overview. The "Filtering" and "Sorting" samples links should be removed
- [x] In the topic: https://dev.igniteui.local/help/iggrid-rest-updating, the sample should be removed.
- [x] In the topic: https://dev.igniteui.local/help/iggrid-responsive-web-design-mode-overview, the sample should be removed.
- [x] In the topic: https://dev.igniteui.local/help/iggrid-responsive-web-design-mode-configuring-column-hiding#related-content, the sample should be removed.
- [x] In the topic: https://dev.igniteui.local/help/iggrid-responsive-web-design-mode-configuring-row-and-column-templates#column-template-example, the samples should be removed.

**Comment by tbelcheva** [comment]
The following topic contains sample for "Conditional Templates" that should be removed: https://staging.igniteui.local/help/conditional-and-advanced-templating-with-angularjs#samples
