### ISSUE TITLE
Broken link to API

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#330]
Go here
https://staging.igniteui.local/help/16.2/igdateeditor-jquery-api

Open this:
igDateEditor ASP.NET MVC Helper API

This is broken:
https://staging.igniteui.local/help/16.2/infragistics.web.mvc~infragistics.web.mvc.datetimeeditormodel

**Comment by damyanpetev** [comment]
Fix already shipped with latest version of the help and will also be updated for the 16.2 deployment shortly. Closing.
