### ISSUE TITLE
No link for ASP.NET MVC Helper API

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#331]
Go here
https://staging.igniteui.local/help/16.2/igcheckboxeditor-jquery-api

Title is "igCheckboxEditor jQuery and ASP.NET MVC Helper API Links", however there is no link for the latter.

**Comment by damyanpetev** [comment]
Fix already shipped with latest version of the help and will also be updated for the 16.2 deployment shortly. Closing.
