### ISSUE TITLE
Grid - API links to older version than the topic version

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#332]
Go here
https://staging.igniteui.local/help/16.2/iggrid-feature-chooser

Open the link to API featureChooserIconDisplay here:
The visibility behavior of the gear icon is controlled by the grid's featureChooserIconDisplay option. 

Link is:
http://www.igniteui.com/help/api/2014.2/ui.iggrid#options:featureChooserIconDisplay
It should be:
http://www.igniteui.com/help/api/2016.2/ui.iggrid#options:featureChooserIconDisplay

**Comment by damyanpetev** [comment]
Fix already shipped with latest version of the help and will also be updated for the 16.2 deployment shortly. Closing.
