### ISSUE TITLE
HierarchicalGrid - API broken links

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#333]
Go here
https://staging.igniteui.local/help/16.2/ighierarchicalgrid-styling-and-theming

Open the links to the MVC Properties in the table Animation reference:
ExpandCollapseAnimation
AnimationDuration
ExpandTooltip
collapseTooltip

All are broken.

**Comment by damyanpetev** [comment]
Fix already shipped with latest version of the help and will also be updated for the 16.2 deployment shortly. Closing.
