### ISSUE TITLE
HTMLEditor API link error

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#334]
Go here
https://staging.igniteui.local/help/16.2/ightmleditor-asp-net-mvc-helper-api

Open the link for igHtmlEditor ASP.NET MVC Helper API:
This is the link
https://staging.igniteui.local/help/16.2/infragistics.web.mvc~infragistics.web.mvc.htmleditormodel
It opens with error. 
![image](https://user-images.githubusercontent.com/9548226/28307148-8d8743e4-6baa-11e7-9bd1-d2d190864b47.png)

**Comment by damyanpetev** [comment]
This should be fixed with the latest version on staging, should be live with the next app update.
