### ISSUE TITLE
igLayoutManager - No ASP.NET MVC Helper API Links

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#335]
Go here
https://staging.igniteui.local/help/16.2/iglayoutmanager-jquery-and-asp.net-mvc-helper-api-links-

The title says: "jQuery and ASP.NET MVC Helper API Links (igLayoutManager)", however there is no link to ASP.NET MVC Helper API.

**Comment by damyanpetev** [comment]
Fix already shipped with latest version of the help and will also be updated for the 16.2 deployment shortly. Closing.
