### ISSUE TITLE
igupload - broken API link

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#337]
Go here
https://staging.igniteui.local/help/16.2/igupload-using-server-side-events
Open the link to AddStartingUploadEventHandler

This link is opened, which is broken 
https://staging.igniteui.local/help/16.2/infragistics.infragistics.web.mvc~addstartinguploadeventhandler

**Comment by damyanpetev** [comment]
Fix already shipped with latest version of the help and will also be updated for the 16.2 deployment shortly. Closing.
