### ISSUE TITLE
igupload - broken link to ServerMessage API

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#338]
Go here
https://staging.igniteui.local/help/16.2/igupload-using-server-side-events

Open the link to ServerMessage here:
 In the event handler add your custom validation logic and if the conditions are not met set a custom ServerMessage and cancel the event.
This link is broken:
https://staging.igniteui.local/help/16.2/infragistics.infragistics.web.mvc~servermessage

**Comment by damyanpetev** [comment]
Fix already shipped with latest version of the help and will also be updated for the 16.2 deployment shortly. Closing.
