### ISSUE TITLE
HTMLEditor - formatting issue causes 1 to appear in text

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#339]
Go here
https://staging.igniteui.local/help/16.2/ightmleditor-adding-ightmleditor
And go here
https://staging.igniteui.local/help/16.2/ightmleditor-adding-combo-to-custom-toolbar

There is a "1" in the text

![image](https://user-images.githubusercontent.com/9548226/28318992-4eb50220-6bd5-11e7-88c8-18147b1c6b01.png)

![image](https://user-images.githubusercontent.com/9548226/28319002-5378005a-6bd5-11e7-98bb-fcbe5d7625b8.png)

**Comment by EmilTanev** [comment]
The second issue causes this as well

![image](https://user-images.githubusercontent.com/9548226/28319095-947507ba-6bd5-11e7-9484-65556f5a8937.png)

**Comment by SlavUI** [comment]
Closing this issue it seems resolved
