### ISSUE TITLE
Scheduler "Adding" topic is missing a title

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/help-topics#345]
Go here:
https://www.igniteui.com/help/igscheduler-adding-igscheduler

Check the first header and the node in the TOC.

I'd expect it to be something like "Adding Scheduler" but instead it's "Topic Overview and Purpose".

**Comment by SlavUI** [comment]
Hi @zdrawku can we close this do are we going to change as suggested ?

**Comment by zdrawku** [comment]
Yes, we are going to fix this in the current Sprint 6
