### ISSUE TITLE
Typos in help topic for igSplitter configuration

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/help-topics#346]
Go here:
[https://www.igniteui.com/help/configuring-igsplitter](https://www.igniteui.com/help/configuring-igsplitter)

Scroll to "Configuring the User Interaction Capabilities" and pay attention on "Property settings" section.

You will come across on some typos on this section. The highlighted "**disable**" word should be changed with "**enable**" and "**collabsible**" should be changed with "**collapsible**". 
Please refer to the attached screenshot!
![img](https://user-images.githubusercontent.com/7037740/30910199-7881f54c-a38c-11e7-9191-c8a8ba60904c.jpg)

**Comment by dianj** [comment]
It seems I don't have access to this site (igniteui.com) and I am not able to make any edits.

**Comment by kdinev** [comment]
@dianj The edits are made into the markdown files in this repository.

**Comment by dianj** [comment]
Thank you. There is a pull request. Please let me know if everything is ok.

**Comment by kdinev** [comment]
@damyanpetev Should this be pulled to branches other than 17.2?

**Comment by damyanpetev** [comment]
@kdinev @dianj If we want the typos fixed in older released versions, then yeah the fix should be to the lowest applicable branch. Otherwise it's okay as it is.

**Comment by alhalama** [comment]
I think the ideal is that we would fix in more than just 17.2 so that if we release updates to the help for the older versions the fix would be included.
