### ISSUE TITLE
"Adding igGrid to a Web Page" height setting

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/help-topics#347]
https://www.igniteui.com/help/iggrid-overview

In the JavaScript for "Adding igGrid to a Web Page", we have the following:
`height: "100%",`
This causes the grid to render very short; I believe the height _has_ to be set by px, otherwise badness ensues. So something more like:
`height: "600px"`

**Comment by dkamburov** [comment]
Having `height: "100%"` may require putting the igGrid inside some other container, which have more specific dimensions.
For example you can take a look at the HTML and see that the grid in the example is inside another container with `height: "300px"`
![image](https://user-images.githubusercontent.com/1182001/31276408-5854c2d0-aaa4-11e7-88b7-014394c0f82d.png)

**Comment by jVanZwieten** [comment]
That's cool that the sample works, however that HTML is not included in the steps, which are now, therefore, misleading. Step #3 says:

> Define a table DOM element, that igGrid will use to render the given data.
> 
> In HTML:
> 
> `<table id="grid"></table>`

So we could either include those div tags into step 3 for no stated reason, or change the grid height to pixels in at least the steps, if not also the sample.

Please note that discrepancies like these may seem trivial, but I found it while demoing the product live to a customer and spending some of our time trying to figure out why it didn't "just work" when I followed the proscribed steps.

**Comment by dkamburov** [comment]
Now I see what you mean, I'll work on improving the topic page.
