### ISSUE TITLE
Broken link to Help topic - Scheduler

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/help-topics#350]
Go here:
https://www.igniteui.com/scheduler/agenda-view

Click here
Schedule Help Overview

Issue:
Broken link
https://www.igniteui.com/help/igscheduler

**Comment by dkamburov** [comment]
The link seems to be already fixed:
https://www.igniteui.com/help/igscheduler-overview

**Comment by SlavUI** [comment]
Closing the issue seems it is resolved.
