### ISSUE TITLE
Broken link to "Configuring ASP.NET MVC (igScheduler)" topic

### ISSUE THREAD

**Issue by dafo** [IgniteUI/help-topics#357]
1. Navigate to https://www.igniteui.com/help/igscheduler-configuring
2. Click "Configuring ASP.NET MVC (igScheduler)"

Actual result: 
Error is shown

Expected result: 
The topic is opened

Note: 
The href attribute is set to "igscheduler-asp-net-mvc-wrapper" and the topic is "04.igscheduler-configure-asp-net-mvc". We should update the filename or the href attribute.

**Comment by alhalama** [comment]
Updating the file name creates broken links if we have ever shared the help topic before so it is better to update the href unless there is a good reason to rename the topic.

**Comment by dafo** [comment]
Thank you, Alan!
I will update the href.
