### ISSUE TITLE
Getting started refers to Angular 2 instead of just Angular

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/help-topics#360]
https://www.igniteui.com/help/getting-started#angular

**Comment by mpavlinov** [comment]
@kdinev This is already fixed here: https://github.com/IgniteUI/help-topics/pull/364/commits/fddf649c2e7491c59a452144b9f521d76e2b06cd and https://github.com/IgniteUI/help-topics/pull/365/commits/f4fcffe2d91432f3d945b98b5c3e241446c3acd7
