### ISSUE TITLE
Missing dependency scripts for igEditors

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/help-topics#376]
Some of the dependency scripts for igEditors are not listed in "[Getting Started with Ignite UI\JavaScript Files in Ignite UI](https://www.igniteui.com/help/deployment-guide-javascript-files#igEditors)".

The full list of topics should look like this:

infragistics.util.js
infragistics.util.jquery.js
infragistics.ui.widget.js
infragistics.ui.scroll.js
infragistics.ui.validator.js
infragistics.ui.notifier.js

**Comment by kdinev** [comment]
Why do the editors depend on the `igScroll`?
