### ISSUE TITLE
Grid > Dependencies: as as

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/help-topics#382]
The word 'as' is repeated in [Grid > Dependencies](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html)

> ### Dependencies
> The grid is exported **as as** an NgModule, thus all you need to do in your application is _to_ import the IgxGridModule inside your AppModule:

**Comment by zdrawku** [comment]
@Hypenate, thank you for pointing that out. I am [moving it](https://github.com/IgniteUI/igniteui-docfx/issues/428) to the appropriate repository.

FYI, for any problem related to documentation you can use [this repo](https://github.com/IgniteUI/igniteui-docfx). If you have problems with samples or stackblitz, you can use [this repo](https://github.com/IgniteUI/igniteui-angular-samples/issues), as for product issues, use [this repository](https://github.com/IgniteUI/igniteui-angular/issues).

**Comment by Hypenate** [comment]
Did I really placed it at the wrong repo again...
Sorry!

**Comment by zdrawku** [comment]
No worries :)
