### ISSUE TITLE
Add note for igTimePicker that setting value runtime, should have the display format

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/help-topics#399]
When setting value in igTimePicker at runtime, setting the value as a string should be according to the display format and cannot accept string ISO values, like "2019-02-21T00:00:00.000Z". In that cases the value should be passed as a [date](http://jsfiddle.net/uwkpx8b0/) in order to work:

$("#timePicker").igTimePicker("option","value", new Date("2019-02-21T00:00:00.000Z"));

This should be added as a not in the API value description or in the igTimePicker topics.

**Comment by sboykova** [comment]
Added a note in the time picker overview topic and not in the API because the time picker value property is inherited from date picker.
